### ISSUE TITLE
Tests not passing

### ISSUE THREAD

**Issue by c11z** [cloud8421/elm.mk#26]
after PR #25 tests do not pass with output
```
elm.mk$ make
...
./tests.sh
test #15 "ls dummy/build/images/test.jpg" failed:
	program terminated with code 2 instead of 0
test #16 "ls dummy/build/images/test.png" failed:
	program terminated with code 2 instead of 0
2 of 20 examples tests failed in 0.017s.
Makefile:4: recipe for target 'test' failed
make: *** [test] Error 1
```

It looks like `build` and `build/images` are part of the INSTALL_TARGETS. Calling make after make install results in the images being cp'd to `build/images/images` which breaks the test. The dist is unaffected because it is not part of the INSTALL_TARGETS and images are cp'd directly from the root images folder.

Removing `build` and `build/images`  from the INSTALL_TARGETS solves the problem.

I am opening a PR, and would love your feedback. Great project by the way.

**Comment by cloud8421** [comment]
Closed by #27
