### ISSUE TITLE
Won't compile if all .elm files are in main src/ dir

### ISSUE THREAD

**Issue by botandrose** [cloud8421/elm.mk#4]
Heya, saw this on elm-discuss. I think this project is a great idea! I replaced my simple Makefile with yours, and tried it out. First issue I ran into was that it requires you two have at least one directory of .elm files inside your /src dir. The project I tried it out in is very simple, and all .elm files are directly in the "root" /src dir. Here's some output demonstrating the issue:

```
$ make
test -s src/Main.elm || echo "$main_elm" > src/Main.elm
make: *** No rule to make target 'src/**/*.elm', needed by 'build/main.js'.  Stop.
$ mkdir src/asdf
$ touch src/asdf/asdf.elm
$ make
test -s src/Main.elm || echo "$main_elm" > src/Main.elm
elm make src/Main.elm --yes --warn --output build/main.js
Success! Compiled 1 modules.                                        
Successfully generated build/main.js
...
```

This would be a PR, but I don't really know make well enough!

**Comment by cloud8421** [comment]
Hi, thanks for looking into the project and the detailed issue report.

You can fix this by removing the`src/**/*.elm` prerequisite here: https://github.com/cloud8421/elm.mk/blob/master/elm.mk#L98

This way, it should work as you expect it.

I'll investigate more though. The default folder/file structure generated by the project looks exactly like yours, so I was expecting this to work.

Would you mind telling me your OS and the output of `make -v`?

Thanks

**Comment by botandrose** [comment]
Cool, that works. Thanks! Ideally, there'd be a way to set it up so that it would work for both scenarios out of the box. Do you think this is possible?

Here is my version info:

```
$ uname -a
Linux mei 3.19.0-51-generic #58-Ubuntu SMP Fri Feb 26 21:22:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.04
DISTRIB_CODENAME=vivid
DISTRIB_DESCRIPTION="Ubuntu 15.04"
$ make -v
GNU Make 4.0
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by cloud8421** [comment]
I think so, I'm about to submit a PR that should do the trick.
